### ISSUE TITLE
Signup Error

### ISSUE THREAD

**Issue by Ninja-Dev-Web** [ERROR404-WEB/SmartNotes#1]
I'm unable to Signup

**Comment by Ninja-Dev-Web** [comment]
Actually  i have hosted the backend server in a free cloud, So it is little bit slow. It may take upto 2 minutes to load.
Sorry for the inconvenience

**Comment by ERROR404-WEB** [comment]
Actually  i have hosted the backend server in a free cloud, So it is little bit slow. It may take upto 2 minutes to load.
Sorry for the inconvenience
